src/_includes/head.html
src/_layouts/default.html

Two versions of google analytics have been found and purged from all source material including the google tag manager v4.
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-148078744-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag() { dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', 'UA-148078744-1');
</script>
<script>(function (w, d, s, l, i) {
w[l] = w[l] || []; w[l].push({
'gtm.start':
new Date().getTime(), event: 'gtm.js'
}); var f = d.getElementsByTagName(s)[0],
j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-MWNB7X4');</script>
and
<script> …

Google Analytics Purged From Site

---

src/api-explorer/v4-0/ConcurRequest.swagger2.json

This documentation update is related to the migration to the Cash Advance v4 API (GA end of September) with a new read scope available end of October
- Cash advance resource tag removed
- Removal of Cash Advance endpoint (Get the detail of an existing cash advance) section
- Removal of cash advance object section

TVR-13706 remove cash advance in Request v4 swagger

---

src/event-topics/request/v4.request-events.md

Given that the new isRecall fact field is available within the Request events, When accessing the Request events specification, Then the isRecall field should be defined.

TVR-14212 [Request ESS] Documentation update

---

src/api-reference/expense/expense-report/expense-report-get.markdown
src/api-reference/expense/expense-report/v3.reports.markdown

-Adding deprecation message to expense-report-get
-Noting that the v3 get report by search criteria endpoint does not return Central Reconciliation reports

EKPZH-799: update customer docs for v2 and v3 report APIs

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Update Spend v4 documentation with restrictions and char length
Users need to know character lengths for fields and chart restrictions.

EMP-953 Update Spend v4 documentation with restrictions and char length

---

src/api-reference/accounting-integration/v4.accountingintegration-account.markdown
src/api-reference/accounting-integration/v4.accountingintegration-list.markdown
src/api-reference/accounting-integration/v4.accountingintegration-mappings.markdown
src/api-reference/accounting-integration/v4.accountingintegration-registration.markdown
src/api-reference/accounting-integration/v4.accountingintegration-request.markdown
src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown
src/api-reference/accounting-integration/v4.accountingintegration-vendor.markdown

- update the ErrorMessage schema to add timestamp and httpstatus
- update Vendor schema to indicate that only first and last name will show in UI
- Update the Mappings API documentation to the latest format (match the service Swagger) to include the IsBillable mapping
- Update Registration API documentation to include the new flag SUPPORTS_LIABILITY_ACCOUNT and what it is used for Also update the flags update documentation to make it clear that they need to send ALL the active flags in the PATCH request, even if some were sent with the POST Registration API.

update Accounting Integration API to reflect product updates

---

src/api-reference/request/v4.endpoints.schemas.markdown

limitation on field size is not well documented
Examples :
classOfService is limited to 32 characters
countryCode is limited to 2 characters
currencyCode is limited to 3 characters

TVR-16354 Next documentation update on Request v4 API

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

This also allows passing actual name as string with value.

Adding `OTHER` as sustainability label provider 

---

src/api-reference/expense/quick-expense/v4.quick-expense.md

Update documentation to reflect location name in the example.

QES-4439 : QE API POST does not create expense with location unless name is given CRMC-197307

---

src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

Lead rate may not be available if property is not available for sale and hence can be left out.

Added clarification that leadRate can be left out if property is closed out

---

.github/ISSUE_TEMPLATE/config.yml

Hi there,
we're working on a central issue template and a central pull request template for all repositories belonging to the open documentation initiative. Once we're ready, these templates will become the default templates for all repositories in the `SAP-docs` org. Since they are specific for the initiative, it doesn't make sense if you use them.
But no worries, we can ignore them for your repository. I saw that you already use your own `PULL_REQUEST_TEMPLATE.md`. To ignore our new issue template, we need to create a folder ISSUE_TEMPLATE with a single `config.yml` file in it. 
I tested this on our local GHES instance.

Create config.yml to ignore default issue templates

---

src/api-explorer/v4-0/ConcurRequest-ea.swagger2.json
src/api-explorer/v4-0/ConcurRequest.swagger2.json

Request Swagger : removing the travelrequest prefix which is already on the base path.

TVR-20473 Request swagger fix

---

src/api-reference/cards/v4.cards-endpoints.account.markdown

Add limitation about test users.
* test users can never be assigned to productive card accounts (only to test accounts)
* test accounts are currently not supported by the Cards v4 API
Test user feature: https://www.concurtraining.com/customers/tech_pubs/Docs/_Current/SG_Shr/Shr_SG_Test_User.pdf

CARDS-8905 Cards v4: Add test user limitation

---

src/api-explorer/v4-0/Cards.oas3.json
src/api-reference/cards/v4.cards-endpoints.schemas.markdown

It does not make sense that partners can send personal card data via the new Cards v4 API because:
* we do not support it technically
* also from a business perspective, the way how it is designed today (enterprise apps setup by client admin) does not allow to integrate personal cards of individual employees
No release notes required, since we know that this is only used by one pilot partner for now.

CARDS-9327 Remove PERS as allowed value for cardProductType

---

src/api-reference/expense/expense-report/v4.expenses.markdown
src/api-reference/expense/expense-report/v4.reports.markdown

Missed a section when previously updating isExpenseRejected documentation (https://github.com/SAP-docs/preview.developer.concur.com/pull/728)

ERS-9789: Finish isExpenseRejected to patch expense documentation

---

src/api-reference/common/connection-requests/connection-requests-resource.markdown

Text forgotten to be removed in Connection Request documentation update.

[LINK-9528] Removing text "(deprecated in v3.2)" from NextPage

---

src/api-explorer/v3-2/ConnectionRequests.swagger.json

Updating the swagger.json file to include the offset parameter and also update the description of the NextPage attribute, according to the changes in the Connection Request API.
Contributors: Wanderson Paes and Alef Farah

Added offset parameter and updated NextPage description

---

src/api-reference/authentication/app-center-learn-more.md

- V4 Attendee docs were moved to under common section, updating the path accordingly.

Fix scopes link for Attendee V4

---

src/api-explorer/v4-0/Reports.swagger.json
src/api-reference/expense/expense-report/v4.reports.markdown

GET /reports/{id} (Get Report Details) endpoint was externalized back in 2018 (related Jira [ERS-1231](https://jira.concur.com/browse/ERS-1231)).  At the time it was externalized the team decided to only open up the TRAVELER and PROXY contexts.  Now we would like to include MANAGER and PROCESSOR contexts for externalization.  In particular, this is to suit the CO approver portal use case where approvers would like to see details of the CO reports to approve.

ERS-13943 - GET /reports/{id} - Include MANAGER and PROCESSOR contexts for externalization

---

src/api-reference/common/attendees/v4.attendees.markdown

Thank you for your reviews @RoAnnC1. Caught this old reference to the field that was removed in https://github.com/SAP-docs/preview.developer.concur.com/commit/8a3be31cd4a75675f024953ad4dab18b7a42829e
Also added default value for further reader / user clarity

ATTEND-1253: Remove Auditing-Related Fields from Schema (clean old ref)

---

.circleci/config.yml

Configuring rubygem to be compatible with ruby 2.7.4

Merge - Configuring rubygem to be compatible with ruby 2.7.4

---

src/api-guides/travel/deeplink-integration.md

Deeplinks for air searches will now only support the following cabin types:
* `ECONOMY`
* `PREMIUM_ECONOMY`
* `BUSINESS`
* `FIRST`

Update cabin types in deeplink-integration.md

---

src/api-guides/travel/deeplink-integration.md

The documentation part of the Travel Deeplink were updated. The information regarding the new DeepLink for the trip details was added to the documentation page of the travel Deeplink.
Also some lines from the already existing documentation were adjusted to a more general way of explaining. Hence the Deeplink documentation is not only for Fligh Search but also for Trip Details readable.

Added Trip details Deep Link Information

---

src/api-reference/expense/expense-report/expense-entry.markdown

- Indicate TransactionAmount is not an allowed field to post for mileage
- Add note stating entries are not allowed to be created on a report that has entered the workflow at least once. (from CRMC-211354)

EKPZH-2564: update expense entry v3 docs

---

src/api-guides/travel/deeplink-integration.md

Only level two headings appear in the link menu on the right. See https://concur-blue.slack.com/archives/C7THTFY3B/p1722590496945179. To allow easy access to the different vertical search deep link sections we need to make them from level three to level two headings.

make vertical search sections appear in link menu

---

src/api-guides/travel/deeplink-integration.md

To support SSO the company uuid can be added as query parameter to a deeplink. No code change was required for this to work, but documentation didn't include it yet.

use query parameter companyuuid to support sso

---

src/api-reference/expense/expense-report/v4.expenses.markdown

* Remove Patch Expense long URL API from developer portal (This API is not externalized yet)
* Remove references to `concur-correlationid` as this is internal only header

ERS-25967: Remove Patch Expense long URL API from developer portal

---

src/api-guides/travel/deeplink-integration-new.md

Previously it was necessary to add the subdomain to a deeplink otherwise an already logged-in user had to log in again when following a deeplink. This issue was now solved and an already logged in user will be directly redirected to the deeplinks destination.

remove subdomains from travel deeplinks

---

src/event-topics/travel/v4.travel-search-events.md

the subtopic field is only used internally by the event service and subscribers cannot see / should not use it. therefore, we remove it from the docu of travel search events

remove only internal available field from travel search event docu

---

src/api-reference/expense/expense-report/v4.workflows.markdown

Expense Report Service developer here, this recent change by support team is not accurate, multiple of our workflow API's do support actions on a processor step. Only a select few of the API's do not and we already have this specified further down in the documentation.
Recent PR that brought this line in:
https://github.com/SAP-docs/preview.developer.concur.com/pull/1250

Revert recent change to Expense Report Service documentation

---

src/api-reference/expense/expense-report/v4.allocations.markdown
src/api-reference/expense/expense-report/v4.comments.markdown
src/api-reference/expense/expense-report/v4.exceptions.markdown
src/api-reference/expense/expense-report/v4.expenses.markdown
src/api-reference/expense/expense-report/v4.reports.markdown

Associated PR:
https://github.com/SAP-docs/preview.developer.concur.com/pull/1283
Changes:
* MANAGER context support properly documented for a variety of endpoints
* `Update submitted report` endpoint had its name, description, and schema updated to better cater to external callers. Concept of 'Short url vs long url' removed from any naming conventions. Description updated to include limitations around when this URL can be used.
* `Get reports to approve`endpoint got a once over with the big change being adding in a proper response schema on top of the example given.
* Comments API updated with the proper employee schema. We do not return `first name`/`last name`/ `middle initial`, we return an `employeeUuid` and `employeeId`

ERS-31031: Whole lot of documentation cleanup and tying up of loose ends

---

src/api-explorer/v3-0/Locations.swagger2.json
src/api-reference/common/locations/v3.locations.markdown

Updating Locations.swagger2.json and markdown file

EXPLOC-2366: Updating Locations.swagger2.json and markdown file

---

src/api-reference/direct-connects/hotel-service-4/v4.endpoints-new.md

Previous [PR](https://github.com/SAP-docs/preview.developer.concur.com/pull/1412) was merged with the incorrect identation, solving with this new one.

fix: [HOTEL-20922] indentation for reshopInfo in hotel rate details request example

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md
src/api-reference/direct-connects/hotel-service-4/v4.schemas.markdown

Hotel connectors have the requirement to highlight specific rates they want to recommend to their customers. To address this need, we are introducing the `highlightedRateText` field in the RateResponse model for the `/hotels/rates` endpoint. This new field is of type string and is optional.

docs: [HOTEL-23694] added highlightedRateText to direct connect documentation 

---

src/event-topics/travel/v4.travel-book-events.md

This PR adds documentation referring to the new `public.concur.travel.book` event.

[EXTRAS-37] Add travel book event docs

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md
src/api-reference/direct-connects/hotel-service-4/v4.schemas.markdown

Add `gdsName` and `pcc` attributes to requestorInfo property.
Both are optional since they are filled only when singlePNR is enabled.

docs: [HOTEL-25800] add GDS name and PCC fields to requestorInfo
