SAP-docs/preview.developer.concur.com

.circleci/config.yml

Kept the default sections and related build commands including the dependency installations. Updated Node version, and integrated build commands from localbuild.sh. Left the echo commands for more granularity in debugging. Build completed successfully.

Circle CI Successful Build Implementation

---

.circleci/config.yml

Adjustments made to build script, was failing on allocations swagger file. It's likely that Python is being used somewhere within the source beyond the underscore and etc scripts.

Updated Config.Yml Circle CI

---

src/_includes/header.html
src/_includes/scripts.html
src/_sass/components/footer.scss
src/_sass/components/navbar-searchbox.scss
src/_sass/components/navbar.scss
src/_sass/components/sidebar.scss
src/_sass/main.scss

Remaining tasks for the Concur Docs team project. Includes the following modifications:
1.) Top navigation should be equally split between the edges / width of the screen. 
2.) The responsiveness for mobile and varying resolutions must be tested and updated to accommodate the width changes made with the side navigation.
+Hamburger mobile navigation has been fixed. 
+Currently working on fixing the mobile responsiveness for the main dual navigation pages. 
+Sweeping through and fixing anomalies throughout other pages as well. 
3.) The ambiguous 9px white padding that is giving way to the bottom navigation must be removed.
4.) The bold font used for the side navigation is not as legible, find a way to make it more legible. 
5.) Search bar opening modal is not attached to the top navigation …

CSS Responsiveness Bug Fixes

---

src/api-reference/request/v4.endpoints.request-resources.markdown
src/api-reference/request/v4.endpoints.schemas.markdown
src/api-reference/request/v4.endpoints.workflow-resources.markdown
src/api-reference/request/v4.get-started.markdown
src/api-reference/request/v4.response-codes.markdown

Markdown changes done:
- v4.get-started.markdown
Dependencies >> List: removal of " Currently in externalisation process, please liaise with List API owner team for further update."
Addition of new travelrequest.externalsystemworkflow.write
- v4.endpoints.schemas.markdown
customField schema >> removal of comment with workaround to retrieve listItemId (note: href was already documented in this schema)
modification of the extensionOf field definition + creation of a new ExtensionOf schema 
addition of the eventRequest field within the Request schema 
- v4.endpoints.response-codes.markdown
Thre new error codes added 
- v4.endpoints.workflow-resources.markdown
Additional section for the External system validation + new scope required
- v4.endpoints.request-resources.markdown
Get the list of …

TVR-13353 Reference page - Request v4 API documentation update

---

src/api-explorer/v4-0/AccountingIntegration.swagger2.json
src/api-reference/accounting-integration/v4.accountingintegration-account.markdown
src/api-reference/accounting-integration/v4.accountingintegration-list.markdown
src/api-reference/accounting-integration/v4.accountingintegration-mappings.markdown
src/api-reference/accounting-integration/v4.accountingintegration-registration.markdown
src/api-reference/accounting-integration/v4.accountingintegration-request.markdown
src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown
src/api-reference/accounting-integration/v4.accountingintegration-vendor.markdown
src/event-topics/event-subscription-topic-accountingintegration.markdown

Changes:
* Added 2 new endpoints to the markdown and the Swagger page
* Reordered the response code in the Swagger page
* Added new content to the Schema page
* Fixed the broken links

Updates Accounting Integration v4 docs 

---

src/event-topics/request/v4.request-events.md

Add a comment "Whenever a Request is approved" and replace report to request a the title

TVR-13872 Update v4.request-events.md

---

src/manage-apps/go-to-market.html

Updated the email for App Center Orientation to the Alliance alias.

Updated orientation email

---

src/manage-apps/go-market-docs/app-center-partner-marketing-toolkit.markdown

Swapped old Qualtrics form links with new working versions

Updating broken Qualtrics links

---

src/api-explorer/v4-0/ConcurRequest.swagger2.json

This reverts commit 7ec05ce6b89cf3042dbe77e052cb24d5cabc0d32, reversing
changes made to d988167d5399efeb24bb33f488887404d07f8a85.

Revert "Merge pull request #136 from quancheng-zhao/TVR-13706-remove-…CA-in-swagger"

---

src/api-reference/common/list-item/v4.list-item.markdown

Fixes the example url in the V4 list-item documentation

Update list-item example request

---

src/api-explorer/v4-0/ConcurRequest.swagger2.json

- Documentation proposal endpoint for GA - Swagger page

TVR-13514 Agency proposal via API v4

---

src/api-reference/expense/quick-expense/v4.quick-expense.md

https://jira.concur.com/browse/QES-974

QES-974 update quick-expense API rate limit

---

src/api-reference/accounting-integration/v4.accountingintegration-account.markdown
src/api-reference/accounting-integration/v4.accountingintegration-list.markdown
src/api-reference/accounting-integration/v4.accountingintegration-registration.markdown
src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown
src/api-reference/accounting-integration/v4.accountingintegration-vendor.markdown

- Modify sample API payloads and responses to be semantically accurate
- Update API descriptions for List and Vendor endpoints to clarify the scope of operations
- Update swagger schema to indicate required attributes

Update `Accounting Integration` API docs

---

src/c405cea951c31015a250d2023263fab5.html

Merge into master branch and then submit a new PR to include the prod version of the Adobe Analytics Snippet.

Adobe Analytics Snippet Integration

---

src/c405cea951c31015a250d2023263fab5.html

Prod Snippet Put Into Dev To Be Merged Back into Prod, we don't need to track metrics for the internal dev site, but moreso the client facing / customer side.

Adobe Analytics Integration of Snippet

---

src/_includes/head.html
src/_includes/scripts.html

Additional locations for global script variable snippet enabling Adobe Analytics.

Additional Global Script Locations For Adobe Analytics

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Update doc for reimbursement type.
https://www.concurtraining.com/customers/tech_pubs/Docs/_Current/SPC/Spc_Shr/Shr_SPEC_Emp_Imp.pdf

USERPROV-633 Update doc for reimbursementType

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Removing restriction for employee number

Removing restriction for employee number

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Update primary attribute for Approver Extension.

USERPROV-0 Update primary attribute for Approver Extension

---

src/api-reference/budget/v4.budget-adjustments.md

Update Budget Item Adjustment to include an optional parameter to improve performance

Update Budget Item Adjustment to include an optional parameter to improve performance

---

src/api-reference/invoice/v4.invoice-pay.markdown

* Updated GET and POST api
* Added BULK api details

Invoice Pay V4 APIs changes

---

src/api-explorer/v4-0/HotelService4.markdown
src/api-explorer/v4-0/HotelService4.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

@kunalshah01  pls take a look at review doc

Hsv4 commits

---

src/manage-apps/go-to-market.html

Updating Teams Link for Partner Orientation

Updating Teams Link

---

src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md
src/api-reference/direct-connects/hotel-service-4/v4.getting-started.markdown
src/api-reference/direct-connects/hotel-service-4/v4.supported-ota-codes.md

PR contains:
1. ADT code list in Supported OTA code file
2. Small fixes (reference to HS2 instead of HS4 and fixed http header info)
3. Updated OTA code list links to point to our supported code file.

adding ADT type OTA codes, updating links to supported OTA codes and other small fixes

---

src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown

Created connectedLists schema and add connectedLists property to the FieldMapping Schema.

update Accounting Integration API to reflect product updates

---

src/api-reference/ess/v4.event-subscription.markdown

Added ESS resource usage section and some minor changes.

ESS resource usage section

---

src/api-reference/expense/expense-report/v4.comments.markdown
src/api-reference/expense/expense-report/v4.expenses.markdown
src/api-reference/expense/expense-report/v4.reports.markdown
src/api-reference/expense/expense-report/v4.workflows.markdown

Latest API changes for Expense Report Service (ERS)
- **Added new properties:** 'fuelTypeListItem', 'receiptImageId', 'stepInstanceId', 'customResponseData', 'expectedWorkflowStepInstanceId', 'expenseRejectedComment'
- **Removed properties:** 'currentProcessInstanceId', 'currentSequence'
- Changed wordings in descriptions

API-Reference update for Expense Report Service (ERS)

---

src/api-reference/direct-connects/hotel-service-4/v4.getting-started.markdown

* Update v4.getting-started.markdown with downloadable links and details about contents of the test tools

Update v4.getting-started.markdown (#4)

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

* Add "isTaxAndFeesInclusive" to documentation

Add documentation for new field (#5)

---

src/api-explorer/v4-1/CashAdvance.markdown
src/api-explorer/v4-1/CashAdvance.swagger2.json

@jonikamelcher Please review and approve

Adding Cash Advance v4.1 APIs

---

src/api-reference/financial-integration/v4.financial-integration.markdown

Minor update to payment reference id description

FINS-2583 PaymentRef description

---

src/api-reference/financial-integration/v4.financial-integration.markdown

Adding Service Codes 213, 295 for payment documents

FINS-1568 Add Service Codes

---

src/api-reference/financial-integration/v4.financial-integration.markdown

Update missing fields in example expense document

FINS-2276 Add fields to expense example

---

src/manage-apps/go-to-market.html

Updating Marketing Office Hours Link

Updating Marketing Office Hours Link

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

- added a list of sustainability providers supported by hsv4

feat: added sustainability provider enums

---

src/api-reference/user-provisioning/v4.user-provisioning.md

Resolving some broken links and adding client info.

Slight edits

---

src/api-reference/accounting-integration/v4.accountingintegration-list.markdown

Approved by: <name(s)> | PR #
Jira URL: https://jira.concur.com/browse/AIS-6758
Describe the change:
- Added table in accounting integration list documentation
- Table provides details on how the endpoint will handle various requests for deleting ERP list names
- Fixed table formatting
What are the acceptance criteria for this change:
- API Documentation has details about how we handle "Delete List Name" requests
How was this tested, and what to look for when testing:
- N/A
Possible impact (additions from reviewers are encouraged):
- N/A
Future work:
- N/A

AIS-6758: ECP - Add details of how we handle deleting of ERP list names to documentation

---

src/api-reference/request/v4.endpoints.request-resources.markdown
src/api-reference/request/v4.endpoints.schemas.markdown
src/api-reference/request/v4.response-codes.markdown

Update RaaS service docs on the latest changes.

TVR-16999 Request API v4 document update

---

src/api-reference/common/list-item/v4.list-item-bulk.markdown

List Item Bulk V4 Update

---

src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown

Jira URL: https://jira.concur.com/browse/AIS-7979
Describe the change:
- Added section about invoicePolicies to AIS documentation
What are the acceptance criteria for this change:
- Documentation is added for invoicePolicies
How was this tested, and what to look for when testing:
- N/A
be updated.

AIS-7979: ECP - Update the Developer Portal documentation for Invoice Policies

---

src/api-explorer/v4-0/Reports.swagger.json

Reverting the breaking changes made to reports swagger in PR 
https://github.com/SAP-docs/preview.developer.concur.com/pull/408/files#diff-e24410df721b5935e911dbcf5973951becc3524717cb7ada1ca239c8d6f6365b

ERS-5825 : Revert the OpenAPI changes for API explorer expense

---

src/api-reference/common/list-item/v4.list-item-bulk.markdown
src/api-reference/common/list-item/v4.list-item.markdown

Add list item naming restrictions
Add advice on delete list items behavior

Update List Item Documentation

---

src/api-reference/financial-integration/v4.financial-documents-schema.markdown
src/api-reference/financial-integration/v4.financial-integration.markdown

[INV-53910](https://jira.concur.com/browse/INV-53910) Updating Financial Integration v4- Invoice documentation with addition of new fields (externalPolicyId, policyName, vendorTaxId)

INV-53910 Update FIS Invoice requestHeader

---

src/api-reference/user-provisioning/spend/v4.spend-user-retrieval.md

USERPROV-0 Update Spend GET Request URL

---

src/api-explorer/v3-1/Vendors.swagger2.json

Adding production URLs (x-servers object) and authentication (security definitions) to the swagger file

INVRAI-657 - Upgrading Vendor v3.1 api documentation

---

src/api-reference/common/list-item/v4.list-item-bulk.markdown

Update the List Item Bulk V4 Documentation to error id in response.

Update Documentation to include Error Id in response

---

src/api-guides/travel/duty-of-care.markdown

Removed plans@concur.com reference (no longer valid)

TRIPSTORE-16095: Update "Duty of Care" markdown

---

src/api-guides/ess-guide.markdown

On Step 5, a few steps (below images) still had bullets. I changed them to numbers to follow the sequence of steps. 
A few alignment of images too, RoAnn.

Updated bullets to numbers

---

src/api-explorer/v4-0/DocumentComplianceGateway.swagger2.json
src/api-reference/document-compliance-gateway/V4.document-compliance-gateway.markdown

Documentation review comments implemented

Documentation review comments implemented

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Update delegation time format and add an example.

USERPROV-0 Update delegation time format

---

src/api-explorer/v4-0/DocumentComplianceGateway.swagger2.json

swagger document review comments implementation.

swagger review comments

---

src/api-reference/request/v4.endpoints.expected-expense-resources.markdown
src/api-reference/request/v4.endpoints.schemas.markdown

Add travelExceptionReasonCodes and allocationFormId in mark downs

TVR-19101 add travelExceptionReasonCodes and allocationFormId in request v4

---

src/api-explorer/v4-0/DocumentComplianceGateway.swagger2.json
src/api-reference/document-compliance-gateway/V4.document-compliance-gateway.markdown

Review comment implementation

---

src/api-explorer/v4-0/Itinerary.swagger2.json

updating swagger docs with additional data

Adding additional Swagger Documentation

---

src/api-reference/common/list-item/v4.list-item-bulk.markdown

1. Clean up formatting
2. Add list item long code explanation and examples
3. Add the rate limit error response
4. Add examples with third/fourth level list items
5. Change url back to us from us2

List Item Bulk API Doc Updates

---

src/api-explorer/v4-0/ListItemBulk.swagger2.json

List Item Bulk API Swagger Update

---

src/api-explorer/v4-0/Reports.swagger.json
src/api-reference/expense/expense-report/v4.cost-objects.markdown

JIRAs:
https://jira.concur.com/browse/ERS-4389
https://jira.concur.com/browse/ARCH-1337

ARCH-1337/ERS-4389: Externalizing the first Workflow API, /costObjectsForApprover

---

src/api-reference/cards/v4.cards-endpoints.schemas.markdown

Formatting fixes for Cards v4 APIs

CARDS-7174 Minor formatting fixes

---

src/api-reference/accounting-integration/v4.accountingintegration-account.markdown
src/api-reference/accounting-integration/v4.accountingintegration-get-started.markdown
src/api-reference/accounting-integration/v4.accountingintegration-list.markdown
src/api-reference/accounting-integration/v4.accountingintegration-mappings.markdown
src/api-reference/accounting-integration/v4.accountingintegration-registration.markdown
src/api-reference/accounting-integration/v4.accountingintegration-request.markdown
src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown
src/api-reference/accounting-integration/v4.accountingintegration-vendor.markdown

Links back to the Getting started page since this will likely never be in the left nav.

Adds links for ease of navigation

---

src/api-reference/financial-integration/v4.financial-documents-schema.markdown
src/api-reference/financial-integration/v4.financial-integration.markdown

FINS-6909 Add merchantTaxId field for Financial Integration documentation.

FINS-6909 Add merchantTaxId field 

---

src/api-reference/profile/v4.identity.md
src/api-reference/user-provisioning/v4.user-provisioning.md

small entitlement clarification

small entitlement clarification 

---

src/event-topics/expense/v4.expense-events.md

Documentation for status changed event published by ERS

ERS-7844: StatusChanged event documentation for external stream

---

src/api-reference/expense/expense-report/v4.reports-temporary.markdown

ERS Project Manager is in need of a temporary preview page that can showcase the new endpoint being reviewed for externalization. This will be deleted and merged with v4.reports.markdown following externalization completion.
https://jira.concur.com/browse/ARCH-1437

Creating a temporary Reports To Approve preview page

---

src/event-topics/expense/v4.expense-events.md

ERS-7844: StatusChanged event documentation re-alignment

---

src/api-explorer/v4-0/List.swagger2.json
src/api-reference/common/lists/v4.list-06-2023.markdown

Add markdown documentation and swagger updates for the Managed Lists and List Filters features.
Created a separate page for the List API so changes are not deployed yet.

LIST-3200 List API Updates - Filters and Managed Lists

---

src/event-topics/index.markdown

Some customers are confused adding https inside https

endpoint example

---

src/api-reference/request/v4.endpoints.cost-objects-resources.markdown

Expecting technical writers to add the same warning banner as for the corresponding Expense page :
https://preview.developer.concur.com/api-reference/expense/expense-report/v4.cost-objects.html

TVR-20472 Request Cost Objects API documentation

---

src/api-reference/request/v4.endpoints.request-resources-ea.markdown
src/api-reference/request/v4.endpoints.workflow-resources-ea.markdown

Contains additions to list of requests and workflow endpoints
List of requests : new query parameter includeDelegateApprovals
Workflow : new query parameter delegatorUserId
The original files have been duplicated in order to create a "hidden" version which can be shared with the early adopter without affecting the official documentation on developer.concur.com

TVR-20473 Request temporary documentation for EA phase of Cost Object Workflow APIs enhancements 

---

src/event-topics/request/v4.request-events-ea.md

new startingStep field
The original files have been duplicated in order to create a "hidden" version which can be shared with the early adopters without affecting the official documentation on developer.concur.com

TVR-20482 Request temporary events documentation for EA phase of Cost Object Workflow APIs enhancements 

---

src/api-explorer/v4-0/UserProvisioning.swagger2.json

Update schema + API description

Provisioning - v4

---

src/api-explorer/v4-0/HotelService.swagger2.json

Doc was updated [earlier](https://github.com/SAP-docs/preview.developer.concur.com/pull/421) back but JSON file was missed

Adding missing updates on payments

---

src/api-reference/common/lists/v4.list-06-2023.markdown

List V4 API Minor wording updates

---

src/api-reference/common/lists/v4.list-06-2023.markdown

List API filters minor update

---

src/api-reference/expense/expense-report/v4.reports-temporary.markdown

Reverts SAP-docs/preview.developer.concur.com#683
Short term reversion, endpoint wont be available until the end of the month.

Revert "ARCH-1437: Deleting temporary reports to approve page, updating original"

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

additional elements added to 
- rating sources: HRS_STAR_RATING
- sustainabilityProvider: GREEN_STAY

HOTEL-10812 correction for rating and sustainability enums

---

src/api-reference/accounting-integration/v4.accountingintegration-account.markdown
src/api-reference/accounting-integration/v4.accountingintegration-get-started.markdown
src/api-reference/accounting-integration/v4.accountingintegration-list.markdown
src/api-reference/accounting-integration/v4.accountingintegration-vendor.markdown

Describe the change:
Updated the documentation. Fixed some links that were broken from reorganizing the accounting integration events wiki page. Added link to the accounting integration events wiki page to the getting started page.

AIS-9091 Improve Partner Documentation for FIP

---

src/api-reference/direct-connects/hotel-service-4/v4.supported-ota-codes.md

add additional rate plan types via OTA codes

HOTEL-10798 add support for new rateplan types

---

src/api-reference/expense/expense-report/expense-entry.markdown

Fixed a bad link due to deprecation move.

Link Update to Expense Entries

---

src/api-reference/preferred_language_locale.md
src/api-reference/profile/v4.identity.md
src/api-reference/user-provisioning/v4.user-provisioning.md

Created a new file to display the preferred Name layout. Will be linked from the identity and profile pages after the location has been determined. 
Thank you

Small changes for date added

---

src/api-reference/common/list-item/v4.list-item-bulk.markdown

Fix the type of the listItem field in the Bulk List Item Error. Thread in #ask channel: https://concur-blue.slack.com/archives/C651HEXNX/p1689613960474449

Fix Bulk List Item Error 

---

src/api-reference/accounting-integration/v4.accountingintegration-registration.markdown
src/api-reference/accounting-integration/v4.accountingintegration-schema.markdown

Update the AIS documentation for the Registration API to include the newly added PostingOptions

AIS-9226 ECP - Add the new posting options to the partner documentation

---

src/api-guides/profile/identity-search.md
src/api-reference/profile/v4.1.identity.md

Reference Changes:
- Enhance introduction
- Enhance /Users/.search description
Guide Changes:
- Remove .search Implementation from title
- Restructure Search Parameters
- Enhance introduction

Identity v4.1

---

src/api-reference/cards/v4.cards-get-started.markdown

Adjusting the getting started into section

CARDS-9302 Update Cards v4 Getting Started

---

src/api-reference/expense/expense-report/v4.workflows.markdown

* Minor updates to Workflows API reference document

ARCH-1205: Minor updates to Workflows API reference document

---

src/api-explorer/v4-1/Identity.markdown
src/api-explorer/v4-1/Identity.swagger2.json

Identity v4.1 Swagger

---

src/api-explorer/v3-0/Attendees.swagger2.json
src/api-reference/expense/attendees/v3.attendees.markdown

Clarify maximum length for Attendee custom fields

ATTEND-1013 Update Attendee V3 documentation

---

src/api-reference/expense/attendees/v3.attendees.markdown

- Deny PUT `SYSEMP` Attendee Type

ATTEND-1011: Deny PUT of SYSEMP Attendee Type

---

src/api-reference/expense/attendees/v3.attendees.markdown

ATTEND-1013 An attendee's type ID cannot be updated

---

src/api-explorer/v3-2/ConnectionRequests.swagger.json

Fixed a few errors pointed by SAP API Metadata Validator
Added:
- "x-sap-shortText"
- "x-servers"
- "securityDefinitions"
Updated:
- "description" from the "info" section
Contributors: Alef Farah, Marc Bell and Wanderson Paes

Update Connection Request swagger file

---

src/api-reference/authentication/app-center-learn-more.md

- Add documentation for the new scopes necessary for V4 Attendee API's.
- Update existing `ATTEND` scope documentation.

ATTEND-1075 - Attendee API scopes documentation

---

src/api-explorer/v4-0/Identity.swagger2.json
src/api-explorer/v4-1/Identity.swagger2.json

Profile Identity v4/v4-1

---

src/api-guides/expense/cost-object-workflow-integration.md

Fixed Get Reports Link in Preview

Integration Guide Updates

---

src/api-guides/e-receipts.markdown

fix the issue in the sample code and add extra explanation to the confusing information in the API document.

Update OTP API samples

---

src/api-reference/common/attendees/v4.attendees.markdown

clarify that private attendees can only be viewed by admins/owner

ATTEND-1304 Enforce IsPublic property from attendee type when retrieving attendee

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md
src/api-reference/direct-connects/hotel-service-4/v4.supported-ota-codes.md

two optional fields added to TotalPrice: feesBreakdown and taxesBreakdown
updated list of supported OTA codes to cover FTT code values

feat: HOTEL-13440 added FTT codes and schema change

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

update docs to support emissions info

feat: update docs for emissions info

---

src/api-explorer/v4-0/Reports.swagger.json
src/api-reference/expense/expense-report/v4.expenses.markdown

Should be merged after the next ERS deployment (4.24.0) - [ERS-15528](https://jira.concur.com/browse/ERS-15528)

ERS-14527 Adding lastModifiedDate to ReportEntrydetail 

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md

Updated docs to support following changes.
Added new cancel penalty description field to CancelPenalties Field inside CancelPenalty is changed from required to optional.

feat: HOTEL-13433 cancel penalty description

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Updating documentation for new fields added in the WorkflowPreferenceExtension

Adding extra fields to the workflow preferences extension

---

src/api-guides/e-receipts-certification.markdown
src/api-guides/e-receipts.markdown

Update check list requirement and add links.

Update check list requirement and add links 

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Add extra info for the reimbursementType field for the Standard entity.

USERPROV-0 Add extra info for the reimbursementType field for the Standard entity

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md
src/api-reference/user-provisioning/spend/v4.spend-user-retrieval.md

Remove invalid query param from the GET doc.

USERPROV-0 Remove invalid query param from the GET doc

---

src/api-reference/ess/v4.event-subscription.markdown

Comments I'm deleting now were only needed for smooth transition between certificates and no longer needed.
Thanks

ESS Removing old and outdated info

---

src/api-reference/expense/expense-report/v4.expense-attendee-associations.markdown

API success review Ticket => https://jira.concur.com/browse/ARCH-1852 
* Design and technical review completed and approved: 
https://jira.concur.com/browse/ARCH-1853 
https://jira.concur.com/browse/ARCH-1854

ARCH-1855: API Launch for API Success Review - v4 POST and DELETE Expense Attendee Associations

---

src/api-reference/expense/expense-report/v4.report-request-associations.markdown

- API Success Review - [ARCH-1859](https://jira.concur.com/browse/ARCH-1859)
- Design Review - [ARCH-1860](https://jira.concur.com/browse/ARCH-1860)
- Technical Review - [ARCH-1861](https://jira.concur.com/browse/ARCH-1861)

ARCH-1862: API Launch for API Success Review - v4 Get Request Associations

---

src/api-guides/travel/deeplink-integration.md

We are adding one more example of usage of Deeplink for Flights Search due to feedback from product team.

SIX-378: Additional deeplink example

---

src/api-reference/document-compliance-gateway/V4.document-compliance-gateway.markdown

Added response code 410 to DCG GET and PUT api documentation

Response code 410

---

src/api-reference/financial-integration/v4.financial-integration.markdown

Updated ignore doc status description

FINS-10923: Update v4.financial-integration.markdown

---

src/api-reference/expense/expense-report/v4.expenses.markdown

* Added isPaperReceiptsReceived attribute to the short URL Update Expense API

ERS-16412: ERS-16412: Externalization: Add 'isPaperReceiptsReceived' to PATCH expense API (Short URL Update Expense API)

---

src/api-reference/user-provisioning/spend/v4.spend-user-retrieval.md

Adding ApprovalLimit to documentation

Adding ApprovalLimit to documentation

---

src/api-guides/travel/deeplink-integration-new.md
src/api-guides/travel/deeplink-integration.md

Updating the existing deep link to shopping results documentation for the upcoming June release. We will release deep links to car, hotel and rail shopping results and update the path of the link for air.

Update deep links to shop results

---

src/api-reference/travelallowance/v4.travelallowance-calculationresults-endpoints.markdown
src/api-reference/travelallowance/v4.travelallowance-itinerary-endpoints.markdown

Adjust order of attributes in response structures for better understandability.

TACS-13576: Reorder some attributes in tavelallowance docs

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.schemas.markdown

Adding exactMatch to HotelProperty object.

Adding ExactMatch field to dev portal

---

src/api-explorer/v4-0/ConcurRequest.swagger2.json
src/api-reference/request/v4.endpoints.schemas.markdown
src/api-reference/request/v4.get-started.markdown
src/event-topics/request/v4.request-events.md

Introduce isPaymentCardRelated field in v4 APIs and events
Update employee schema doc to remove href and template

TVR-23910 Concur Request doc update

---

src/api-reference/request/v4.endpoints.schemas.markdown

Update the description of the returnLeg attribute

TVR-24073 Concur Request doc update

---

src/api-reference/spend-documents/v4.spend-documents.markdown

Added API Documentation for the Spend Document suite of APIs.

RCPT-60428 - External API Documentation for Spend Documents API

---

src/api-reference/spend-documents/v4.spend-documents.markdown

RCPT-60428 - Update v4.spend-documents.markdown

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

USERPROV-1681 Update Approver Limit Schema

---

src/tools-support/release-notes/api/archive/2024-07-10
src/tools-support/release-notes/index.markdown

Created the file, adjustments needed.

Created July RN

---

src/api-reference/cards/v4.cards-endpoints.schemas.markdown
src/api-reference/cards/v4.cards-endpoints.transaction.markdown
src/api-reference/cards/v4.cards-get-started.markdown

Adding the following infos as requested in https://jira.concur.com/browse/CARDS-12254
- Request payload size limit
- Rate limit
- Transactions are dependent on accounts
- Available data centers

CARDS-12254: Update Cards V4 Developer Documentation

---

src/api-reference/travelallowance/v4.travelallowance-get-started.markdown

Add a clarification to the public API documentation to clarify that these APIs are relevant for New TA only.

TACS-14006 Add a clarification: API only for TA service

---

src/api-guides/travel/deeplink-integration-new.md
src/api-guides/travel/deeplink-integration.md

In October we will support airport selection, if an airport is missing in an air deeplink, and we will support hotel property IDs from different sources like GDS in hotel deeplinks. Additionally we are adding a troubleshooting section to the docu for common error messages. Texts were reviewed by Product Manager

Update travel deeplinks docu with features for October

---

src/api-reference/expense/expense-report/v4.workflows.markdown

API Success Review Ticket => ARCH-1980
API Launch for API Success Review (Submit Report) => ARCH-1983

ERS-17393: API Launch for API Success Review - Submit Report

---

src/api-reference/expense/quick-expense/v4.quick-expense.md

https://jira.concur.com/browse/QES-5834
It was reported that the file size allowed for uploading is incorrectly pspecified in the docs.Confirmed the size with imaging team and rectifying the same

QES-5834-Changing the permissible upload file size

---

src/api-reference/ess/v4.event-subscription.markdown

Small but very important change
We shifted from update in January to Sep-Oct updates, this phrase was no longer valid. 
If possible please deploy today or Monday.

ESS certificate change small fix

---

src/api-guides/travel/deeplink-integration.md
src/event-topics/travel/v4.travel-search-events.md

this will not change how the content is displayed, but improves the readability while editing

format tables for better readability while editing

---

src/api-reference/expense/expense-report/expense-entry.markdown

Comment field was never implemented for v3 api. Need to add disclaimer explaining how this field is not functional.

EKPZH-3087: add disclaimer to comment field

---

src/api-guides/travel/deeplink-integration-new.md

This PR adds the docu for a new deeplink feature: a deeplink to add a hotel booking to an existing trip

Add travel deeplink docu for add hotel to trip feature

---

src/api-reference/profile/v4.1.identity.md
src/api-reference/profile/v4.identity.md
src/api-reference/user-provisioning/v4.user-provisioning.md

Added clarification for the removal of PN.

Preferred name description updates

---

PULLMERGE.md

Added a "Note"

---

src/api-reference/expense/expense-report/v4.exceptions.markdown

Fixing a table formatting issue I brought in via a previous PR:
https://github.com/SAP-docs/preview.developer.concur.com/pull/1283

ERS-31031:Formatting fix

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md
src/api-reference/user-provisioning/v4.user-provisioning.md

Updating to remove ADP and replace with payroll

Updating to remove ADP and replace with payroll

---

src/api-reference/authentication/apidoc.markdown

Reverts SAP-docs/preview.developer.concur.com#1301

Revert "Updated the Base URIs and Authorization grant sections"

---

src/api-reference/user-provisioning/spend/v4.spend-user-extension-schema.md

Update the description for the CustomData field.

USERPROV-0 Update the description for the CustomData field

---

src/api-reference/user-provisioning/spend/v4.spend-form-fields.md

V4 Form Fields

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.schemas.markdown

Update Hotel Service Swagger to add safetyScore field in hotel property schema.

[HOTEL-20422] docs(hs4): add safetyscore to hotelproperty

---

src/event-topics/expense/v4.expense-events.md

-  Added `reportType` property to PubSub events.

ERS-32563: Updated expense events page to the latest

---

src/manage-apps/go-market-docs/app-center-partner-marketing-toolkit.markdown

Requested on [Jan 29, 2025] by
Danielle Martin |Partner Marketing Operations, Global Partner Mktg. 
SAP Concur | danielle.martin01@sap.com

deleted "Marketing Office Hours

---

src/event-topics/profile/v4.travel-events.md

Updating the documentation to align with the current behavior.

Updating docs related to travel-profile events

---

src/api-reference/travelallowance/v4.travelallowance-get-started.markdown

Update with dependency to Locations v3

TACS-15744 Update Documentation - Getting Started Page

---

src/api-reference/authentication/app-center-learn-more.md

Ref. https://github.com/SAP-docs/preview.developer.concur.com/pull/1334/files

Added new scope

---

src/api-reference/common/lists/v4.list.markdown

Adds externalThreshold to v4 ListResponse

Add ExternalThreshold to List v4 ListResponse

---

src/api-reference/user-provisioning/spend/v4.1.spend-form-fields.md

Update and rename v4.spend-form-fields.md to v4.1.spend-form-fields.md

---

src/api-reference/user-provisioning/spend/v4.1.spend-form-fields.md

EMP-12473 Update FF V4.1 Preview doc

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

Update query param for v4.1.spend-user-retrieval.md

USERPROV-0 Update query param for v4.1.spend-user-retrieval.md

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

Update query param in the response of v4.1.spend-user-retrieval.md

USERPROV-0 Update query param in the response of v4.1.spend-user-retrieval.md

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

USERPROV-0 Add info for Standard entity

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

Update Country to Country/Region.
<details>
<summary>Request</summary>
```shell
```
</details>
<details>
<summary>Response</summary>
```json
```
</details>

USEERPROV-0 Update Country to Country/Region

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

Remove line break element, it's not rendering properly on the developer portal website.

USERPROV-0 Update v4.1.spend-user-retrieval.md

---

src/event-topics/expense/v4.expense-events-new.md

- Adds the description for the new expense report event `reportCreated` to the event documentation.
- Fixes minor errors in the existing `statusChanged` event description.

ERS-32617: New event reportCreated added for Expense Report Service (ERS)

---

src/event-topics/expense/v4.expense-events-new.md

Review feedback for the reportCreated event.

ERS-32617: PR review feedback for reportCreated event

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

Add GET examples for ApproverLimit Config extension.

USERPROV-0 Add GET examples for ApproverLimit Config extension

---

src/api-reference/user-provisioning/spend/v4.1.spend-form-fields.md

Update List field of the FF V4.1 doc.

USERPROV-0 Update List field of the FF V4.1 doc

---

src/api-reference/travelallowance/v4.travelallowance-itinerary-endpoints.markdown

Add itinerary changing APIs to documentation. The API is in technical Review: https://jira.concur.com/browse/ARCH-2112

ARCH-2112: New Public Travel Allowance APIs

---

src/api-reference/travelallowance/v4.travelallowance-itinerary-endpoints.markdown

Reverts SAP-docs/preview.developer.concur.com#1368

Revert "ARCH-2112: New Public Travel Allowance APIs"

---

src/api-reference/user-provisioning/spend/v4.1.spend-user-retrieval.md

Add "ne" to the customData field.

USERPROV-0 Add "ne" to the customData field

---

src/api-reference/travelallowance/v4.travelallowance-itinerary-endpoints.markdown

Reverts SAP-docs/preview.developer.concur.com#1406

Revert "Revert "ARCH-2112: New Public Travel Allowance APIs""

---

src/api-reference/user-provisioning/spend/v4.1.spend-form-fields.md

Add "Name" field to the FormField V4.1 doc.

USERPROV-0 Add "Name" field to the FormField V4.1 doc

---

src/api-reference/locale-codes.markdown

Reverts SAP-docs/preview.developer.concur.com#1421

Revert "Update locale-codes.markdown"

---

src/api-guides/travel/deeplink-integration.md

Removing mobile exception from travel deep link docs

update mobile deep link docs

---

src/api-reference/direct-connects/hotel-service-4/v4.endpoints-new.md

Reverts SAP-docs/preview.developer.concur.com#1484

Revert "fix: [HOTEL-20922] indentation for reshopInfo in hotel rate details request example"

---

src/api-reference/expense/expense-config/v4.expense.config.markdown

Reverts SAP-docs/preview.developer.concur.com#1499

Revert "Revert "ECS-7827: add new expense config v4 APIs""

---

src/api-reference/common/attendees/v4.attendees.markdown

Reverts SAP-docs/preview.developer.concur.com#1540

Revert "ATTEND-2506 Clarify duplicate attendee handling."

---

src/api-explorer/v4-0/HotelService.swagger2.json
src/api-reference/direct-connects/hotel-service-4/v4.endpoints.md
src/api-reference/direct-connects/hotel-service-4/v4.schemas.markdown

feat: HOTEL-22279 added hrefs field in direct-connect schema for hotel

---

src/api-reference/direct-connects/hotel-service-4/v4.schemas.markdown

This PR fix an error from rebase/merge branch

fix: removed wrong inline

---

src/api-reference/common/attendees/v4.attendees.markdown

Reverts SAP-docs/preview.developer.concur.com#1551

Revert "Revert "ATTEND-2506 Clarify duplicate attendee handling.""

---

src/api-explorer/v3-0/Reports.swagger2.json

Update approvalStatusName description for v3 reports API

EKPZH-3676 Update approvalStatusName description

---

src/api-reference/ess/v4.event-subscription.markdown

EVENT-113267 - Updating ESS certificate + key

---

src/api-reference/ess/v4.event-subscription.markdown

Added troubleshooting info
